version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.21.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:4444/wd/hub/status || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

  chrome:
    image: selenium/node-chrome:4.21.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:7900" # <--- ADDED: Maps host port 5900 to container's VNC port 7900

  firefox:
    image: selenium/node-firefox:4.21.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5901:7900" # <--- ADDED: Maps host port 5901 to container's VNC port 7900 for Firefox (using a different host port to avoid conflict)

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      chrome:
        condition: service_started
      firefox:
        condition: service_started
      selenium-hub:
        condition: service_healthy
    volumes:
      - .:/code
      - ./test:/app/test      # ✅ Ensure test directory is shared
      - ./result.txt:/app/result.txt    # ✅ Map result.txt to host for Jenkins
    working_dir: /app
    environment:
      - SELENIUM_HUB=http://selenium-hub:4444/wd/hub
    command: ["python", "test/test_google_search.py"] # Assuming this is your current test file

